### ISSUE TITLE
jakarta.xml.bind absent in jakarta.jakartaee-bom:8.0.0

### ISSUE THREAD

**Issue by grossws** [eclipse-ee4j/jakartaee-api#101]
JAXB API is present in jakartaee-api module as optional compile-time dep and in parent but not in BOM. It's present in 9.0.0 BOM.

JAXB mentioned as present in [spec](https://jakarta.ee/specifications/platform/8/platform-spec-8.pdf) since it assumes Java SE 8 where it was in `rt.jar`. On JDK11+ we need to add `jakarta.xml.bind-api` explicitly.

It would be very convenient if it could be added to 8.x BOM.

**Comment by kwsutter** [comment]
@grossws Can you suggest a proposed update via a PR?  We have a 8.0.x-BRANCH.  I'm just not exactly clear on what you think should be updated in the 8.0.x BOM.  And, is the 9.0.x and proposed 9.1.0 BOM okay with regards to JAXB?  We're trying to finalize 9.1, so I want to ensure that we have that BOM correct.  And, then we can try to get the 8.0.x BOM cleaned up.  Thanks!

**Comment by grossws** [comment]
@kwsutter, ok I'll create a PR with jaxb-api for 8.x.

`master` and `9.1.0-RC1-BRANCH` both have `jakarta.xml.bind:jakarta.xml.bind-api` in BOM, so all is perfect there already.

**Comment by keilw** [comment]
Interesting, so unlike Microprofile which had a BOM and then threw it away Jakarta EE does have one?
It's not this one, is it: https://guicedee.com/

**Comment by grossws** [comment]
@keilw, No, it's quite different.

His project has quite different scope. Jakarta EE is standardized environment with quite rigid versioning scheme. You can't jump say Servlet API from 4.x to 5.x in Jakarta EE 8 since a lot of people (including Glassfish/Wildfly/TomEE/WebLogic/WebSphere/Tomcat/Jetty/Undertow/Spring/OpenLiberty developers and users) are implementing or depending on some EE standard APIs in major version with guarantee of some mid/long-term support for their users. 

@GedMark has project-local bom with different jakarta apis like many do. He just grouped them in one place I think.

**Comment by keilw** [comment]
@grossws I guess at least the way he offers to use JPMS I think we could learn a bit from what he's doing.

**Comment by grossws** [comment]
And if I understand correctly Eclipse Microprofile merged bom into main repo: https://github.com/eclipse/microprofile#maven-bill-of-materials-pom

**Comment by grossws** [comment]
I feel that JPMS is orthogonal to BOMs since they are just curated POM files with bunch of `dependencyManagement` blocks.

It's more relevant to api/spi/impl jars. For example jaxrs-api [has module-info.java](https://github.com/eclipse-ee4j/jaxrs-api/blob/master/jaxrs-api/src/main/java/module-info.java) to support modules. I don't use jpms myself since I unfortunately have some deps that are in java 1.6-1.8 era and they aren't going to migrate for years if at all.

**Comment by keilw** [comment]
Maybe but the name is all but intuitive but at least some demos like that conference app now also seem to use it. 
Many of the vendors now have their own tutorials expecially for MicroProfile so that's why the one at Eclipse is never so well-maintained. 
Also similar here, because the [tutorial-examples POM](https://github.com/eclipse-ee4j/jakartaee-tutorial-examples/blob/master/pom.xml) does not use the BOM, in fact I have not seen a demo use it, they mostly rely on the "platform-api-pom" instead.

**Comment by grossws** [comment]
It's mostly because jakartaee-bom and jakartaee-api have different target groups: api pom is for platform users who wish to develop application using Jakarta EE platform (like CDI and `jakarta.inject` annotations, JAX-RS etc). BOM on the other hand is most useful for library and server developers (libs like Weld/Jersey/Resteasy and servers like Apache Tomcat, Eclipse Jetty, Eclipse GlassFish, JBoss WildFly, IBM OpenLiberty etc).

I'm not quite sure how well is [Jakarta EE tutorial](https://eclipse-ee4j.github.io/jakartaee-tutorial/) is maintained but it's quite comprehensive if a bit enterprise-y, but we're talking about descendant of Java version 2 Enterprise Edition xD

I personally prefer JBoss docs for relevant componets (like weld and resteasy) with cross-referencing them against specifications to grok what is the standard and what is vendor-deviation/"extension". But it might be a bit too in depth for many.

**Comment by GedMarc** [comment]
However that is no reason to keep technology back,
Bottom line really is if there isn't any modular information, the library is not JDK 11 compatible. You cannot use jlink, jmod or jpackage in any way, and you are forced to run in classpath mode with warnings of do not deploy to maven

The Jakarta framework is not compatible currently with JDK11, it is backwards compatible, but does not have any support for the new Java technology.

The release of EE, and specifying compatibility for 11, is false.

**Comment by GedMarc** [comment]
I've gone through quite a few variations from JDK 9 to 16, finally settling on a way to do it that manages +-350 projects with ease, and updates - 

Thank you so much guys for the recognition on GuicedEE - it really was a lot of work over a lot of years :) 

It would be a pleasure to share any information I might have gained during the development of it

**Comment by keilw** [comment]
Why don't you join the [Plattform Call](https://docs.google.com/document/d/1EJ2ilaPhMnQqa3aw6AmwjRbBPGL3_np4uuwklgfqPZI/edit?usp=sharing) at some point, this BOM topic was also brushed in the agenda (I had a longer meeting with a client so I could not join yesterday) and I think the meeting is fairly open, I cannot say if you need to sign an Eclipse Contributor agreement but if so @kwsutter or @ivargrimstad can tell you.

**Comment by kwsutter** [comment]
> @kwsutter, ok I'll create a PR with jaxb-api for 8.x.
> 
> `master` and `9.1.0-RC1-BRANCH` both have `jakarta.xml.bind:jakarta.xml.bind-api` in BOM, so all is perfect there already.

Thank you, @grossws!  I've added comments to your PR #103.  I just may need some education on how this BOM will be used with Jakarta EE 8.0.x.

**Comment by starksm64** [comment]
PR merged
