### ISSUE TITLE
[JakartaEE 9.1] Missing release json-api 2.0.1

### ISSUE THREAD

**Issue by fanste** [eclipse-ee4j/jakartaee-api#105]
Jakarta EE 9.1 references the version 2.0.1 of the json-api which is not available:
![grafik](https://user-images.githubusercontent.com/3531183/119655884-5c37d980-be2a-11eb-8fe2-8ef794564c44.png)

Source: https://mvnrepository.com/artifact/jakarta.platform/jakarta.jakartaee-web-api/9.1.0
(and the error in my IDE)

**Comment by ivargrimstad** [comment]
Thanks!
JSON-P is in the staging. I have pinged them to get it released to maven central.

**Comment by ivargrimstad** [comment]
It is now available in Maven Central

https://search.maven.org/artifact/jakarta.json/jakarta.json-api/2.0.1/jar
