### ISSUE TITLE
merge 8.0.0-BRANCH into master

### ISSUE THREAD

**Issue by bshannon** [eclipse-ee4j/jakartaee-api#42]
Now that the release is done, the 8.0.0-BRANCH branch needs to be merged
into master and deleted.

**Comment by kwsutter** [comment]
I just did a compare from the 8.0.0-BRANCH to Master and they look identical -- except for the errant extra -SNAPSHOT for the version in the pom file.  We do need to update Master for the 9.0.0-SNAPSHOT, but otherwise I see no reason to do this merge.

**Comment by bshannon** [comment]
Yes, once the release is committed, the 8.0.0-BRANCH needs to be merged back into
master.  In other words, many weeks ago!

Please do it ASAP so we can move master ahead for 9.0.0.

**Comment by kwsutter** [comment]
I created a draft PR #50 to demonstrate my hesitancy with doing this merge.  Take a look.  The only differences are the incorrect update to the Version (extra -SNAPSHOT), so I see no reason to do this issue or the PR.  I still agree that we need to update Master with the 9.0.0-SNAPSHOT, but it's not done via this merge...

**Comment by kwsutter** [comment]
This Issue is no longer required.  We have modified the pom in master to be ready for 9.0.0-SNAPSHOT.  And, if we do need to create a maintenance release (ie. 8.0.1), then we'll create a branch at that time.
