### ISSUE TITLE
dependency version of jakarta.persistence-api in jakarta.jakartaee-bom broken on Branch 8.0.0-BRANCH

### ISSUE THREAD

**Issue by thomaswoehlke** [eclipse-ee4j/jakartaee-api#44]
on Branch 8.0.0-BRANCH the dependency version of jakarta.persistence-api is broken in File:

jakartaee-bom/pom.xml line 118-122

           <dependency>
                <groupId>jakarta.persistence</groupId>
                <artifactId>jakarta.persistence-api</artifactId>
                <version>${jakarta-persistence-api.version}</version>
            </dependency>

There is no property jakarta-persistence-api.version set, but there is a property in the Parent pom.xml line 57

 <jakarta.persistence-api.version>2.2.3</jakarta.persistence-api.version>

Suggestion:

change jakartaee-bom/pom.xml line 121 to:

<version>${jakarta.persistence-api.version}</version>

Signed-off-by: Thomas Wöhlke <thomas.woehlke@gmail.com>

**Comment by kwsutter** [comment]
Resolved via PR #49.
