### ISSUE TITLE
Missing LocalStrings for javax.servlet in jakarta-platform 8.0.0

### ISSUE THREAD

**Issue by kalgon** [eclipse-ee4j/jakartaee-api#61]
Some classes from `javax.servlet` which are bundled in jakarta-platform are using `LocalStrings.properties` resource bundles but those are not present in the maven central distribution.

Classes which are using `LocalStrings.properties` (from `javax.servlet` or `javax.servlet.http`) are: `GenericFilter`, `GenericServlet`, `ServletOutputStream`, `Cookie`, `HttpServlet` and `HttpUtils`.

Strangely, the jakarta-platform:jakartaee.jakartaee-api:8.0.0 (sources) contains all those `LocalStrings.properties` but the jar does not.

**Comment by kwsutter** [comment]
@kalgon, can you verify if Issue https://github.com/eclipse-ee4j/jakartaee-api/issues/59 resolves this problem for you?  It seems that @markt-asf's solution was generic to pick up missing properties files in several projects.  But, if you could verify that it resolves your issue, it would be appreciated.  If not, if you could suggest a PR that might help the situation identified by your issue, that would be great. Thanks!

**Comment by kwsutter** [comment]
Due to the lack of activity, I'm going to just close this Issue out.  @kalgon, if you feel there is still an issue, please re-open with additional information on what's still broke.  Thanks!
